# =================================================================
# Configurazione Mosquitto per Progetto Serra Intelligente
# =================================================================

# Ascolta sulla porta standard 1883 su tutte le interfacce di rete
listener 1883 0.0.0.0

# Consente connessioni senza credenziali (necessario per i client WoT di prova)
allow_anonymous true
